language: csharp
solution: ./src/csmacnz.Coveralls.sln
install:
  - curl -sS http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip > /tmp/pcl-assemblies.zip
  - unzip /tmp/pcl-assemblies.zip -d /tmp/pcl-assemblies && mv /tmp/pcl-assemblies/PortableReferenceAssemblies-2014-04-14 /tmp/pcl-assemblies/.NETPortable
  - export XBUILD_FRAMEWORK_FOLDERS_PATH=/tmp/pcl-assemblies/
  - export MONO_INTEGRATION_MODE=BASH
  - export MONO_INTEGRATION_MONOPATH=/usr/bin
  - nuget restore ./src/csmacnz.Coveralls.sln
  - chmod +x ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe
script:
  - xbuild /p:Configuration=Release ./src/csmacnz.Coveralls.sln
  - mono ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/csmacnz.Coveralls.Tests/bin/Release/csmacnz.Coveralls.Tests.dll
  - mono ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/csmacnz.Coveralls.Tests.Integration/bin/Release/csmacnz.Coveralls.Tests.Integration.dll
