language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
sudo: false
install:
  - export LINUX_INTEGRATION_MODE=True
  - dotnet restore ./csmacnz.Coveralls.sln
script:
  - dotnet build ./csmacnz.Coveralls.sln
  - dotnet test ./src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj