language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
sudo: false
install:
  - export COVERALLSNET_EXEPATH=Package/Archive/ubuntu/csmacnz.Coveralls
  - dotnet restore ./csmacnz.Coveralls.sln
script:
  - dotnet build ./csmacnz.Coveralls.sln -c Release
  - dotnet test ./src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj -c Release
  - dotnet publish ./src/csmacnz.Coveralls/csmacnz.Coveralls.csproj -f netcoreapp1.1 -c Release -o "../../Package/Archive/ubuntu" -r ubuntu.14.04-x64
  - dotnet test ./src/csmacnz.Coveralls.Tests.Integration/csmacnz.Coveralls.Tests.Integration.csproj -c Release