version: 0.0.{build}
image: 
- Visual Studio 2017 Preview
- ubuntu
environment:
  COVERALLS_REPO_TOKEN:
    secure: /6Ynh8LMsDKryTdOsEc2zl0ePsN3ce+oYemlM6CFK3ChePYSavZmgIH1ENWE0ZDh
  COVERITY_TOKEN:
    secure: eJdOjCT+V5sq+EWTsuBwx8r47EHFutwOxnA2+yhdA2E=
  COVERITY_EMAIL:
    secure: YNNLrvdTPJBtXcWskGnutoOOXbWeulhguf0c7iX9Gis=
cache:
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- cmd: powershell .\build.environment.ps1
- cmd: psake appveyor-install
- sh: printf "Commands with sh Prefix run on Linux image only"
- sh: sudo apt-get update
- sh: sudo apt-get install dotnet-sdk-2.1.300-preview2-008533 -y
build_script:
- ps: Write-Host "APPVEYOR=$env:APPVEYOR"
- cmd: psake appveyor-build
- sh: dotnet build -c Release
test_script:
- cmd: psake appveyor-test
- sh: dotnet test src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../
- sh: dotnet run -c Release --project src/csmacnz.Coveralls/csmacnz.Coveralls.csproj -- --opencover -i "coverage.xml" --treatUploadErrorsAsWarnings
artifacts:
- path: TestResults/Coverage.xml
  name: Coverage.xml
- path: Package/coveralls.net.*.zip
- path: Package/coveralls.net.*.nupkg
deploy:
- provider: GitHub
  release: $(GitVersion_SemVer)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/,/.*\.zip/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
