version: 0.3.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7+M7//b+83bTse+910JEiExhI3kRpPNByeBKgndUaWmjCmdJglS2Hermr2V2MabW
install:
- ps: .\build.environment.ps1
- ps: GitVersion /output buildserver /updateassemblyinfo true /assemblyVersionFormat Major
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: opencovertests.xml
  name: opencovertests.xml
- path: coveralls.net.*.zip
- path: coveralls.net.*.nupkg