version: 0.0.{build}
image: Visual Studio 2017 Preview
environment:
  COVERALLS_REPO_TOKEN:
    secure: /6Ynh8LMsDKryTdOsEc2zl0ePsN3ce+oYemlM6CFK3ChePYSavZmgIH1ENWE0ZDh
  COVERITY_TOKEN:
    secure: eJdOjCT+V5sq+EWTsuBwx8r47EHFutwOxnA2+yhdA2E=
  COVERITY_EMAIL:
    secure: YNNLrvdTPJBtXcWskGnutoOOXbWeulhguf0c7iX9Gis=
cache:
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- cmd: curl -O https://download.microsoft.com/download/2/9/3/293BC432-348C-4D1C-B628-5AC8AB7FA162/dotnet-sdk-2.1.3-win-x64.exe
- cmd: dotnet-sdk-2.1.3-win-x64.exe /install /quiet /norestart /log install.log
- ps: .\build.environment.ps1
- ps: psake appveyor-install
build_script:
- ps: psake appveyor-build
test_script:
- ps: psake appveyor-test
artifacts:
- path: TestResults/Coverage.xml
  name: Coverage.xml
- path: Package/coveralls.net.*.zip
- path: Package/coveralls.net.*.nupkg
deploy:
- provider: GitHub
  release: $(GitVersion_SemVer)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
