version: 0.{build}
os: Windows Server 2012 R2
environment:
  COVERALLS_REPO_TOKEN:
    secure: /6Ynh8LMsDKryTdOsEc2zl0ePsN3ce+oYemlM6CFK3ChePYSavZmgIH1ENWE0ZDh
  COVERITY_TOKEN:
    secure: eJdOjCT+V5sq+EWTsuBwx8r47EHFutwOxnA2+yhdA2E=
  COVERITY_EMAIL:
    secure: YNNLrvdTPJBtXcWskGnutoOOXbWeulhguf0c7iX9Gis=
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: opencovertests.xml
  name: opencovertests.xml
- path: coveralls.net.*.zip
- path: coveralls.net.*.nupkg
